// <auto-generated />
using System;
using Caliber.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caliber.Api.Data.Migrations
{
    [DbContext(typeof(CaliberDbContext))]
    [Migration("20260820114839_SettingsAndSkillLifecycle")]
    partial class SettingsAndSkillLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Caliber.Api.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ExpiryWarningDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IssuingBody")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("bit");

                    b.Property<int?>("ValidityMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("Caliber.Api.Domain.CertificationAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AwardedOn")
                        .HasColumnType("date");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EmployeeCertificationId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresOn");

                    b.HasIndex("EmployeeCertificationId", "AwardedOn")
                        .IsDescending(false, true);

                    b.ToTable("CertificationAwards");
                });

            modelBuilder.Entity("Caliber.Api.Domain.CertificationSkill", b =>
                {
                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiency")
                        .HasColumnType("int");

                    b.HasKey("CertificationId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CertificationSkills");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalEmployeeNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JobRoleId");

                    b.HasIndex("LocationId", "JobRoleId", "IsActive");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AssignedOn")
                        .HasColumnType("date");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("EmployeeId", "CertificationId")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("EmployeeCertifications");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("AssessedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceCertificationId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceEmployeeCertificationId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceEmployeeTrainingId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceTrainingProgramId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresOn");

                    b.HasIndex("SourceCertificationId");

                    b.HasIndex("SourceEmployeeCertificationId");

                    b.HasIndex("SourceEmployeeTrainingId");

                    b.HasIndex("SourceTrainingProgramId");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "SkillId")
                        .IsUnique();

                    b.HasIndex("SkillId", "ProficiencyLevel");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("AcknowledgedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("AssignedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("NextDueOn")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextDueOn");

                    b.HasIndex("TrainingProgramId");

                    b.HasIndex("EmployeeId", "Status");

                    b.HasIndex("EmployeeId", "TrainingProgramId")
                        .IsUnique();

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("EmployeeCertificationId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeSkillId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeTrainingId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UploadedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("VerifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCertificationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeSkillId");

                    b.HasIndex("EmployeeTrainingId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("Caliber.Api.Domain.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Caliber.Api.Domain.RoleModuleAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevel", "ModuleKey")
                        .IsUnique();

                    b.ToTable("RoleModuleAccess");
                });

            modelBuilder.Entity("Caliber.Api.Domain.RoleRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int?>("DueWithinDaysOfHire")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumProficiency")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("SkillId");

                    b.HasIndex("TrainingProgramId");

                    b.HasIndex("JobRoleId", "Kind");

                    b.ToTable("RoleRequirements");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Caliber.Api.Domain.SkillAssignmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedProficiency")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ReviewedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("ReviewedByEmployeeId");

                    b.HasIndex("SkillId");

                    b.HasIndex("EmployeeId", "SkillId", "Status");

                    b.ToTable("SkillAssignmentRequests");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EstimatedDurationHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("TrainingModules");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("EstimatedDurationHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ExpiryWarningDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("RecurrenceMonths")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAcknowledgement")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingProgramSkill", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiency")
                        .HasColumnType("int");

                    b.HasKey("TrainingProgramId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("TrainingProgramSkills");
                });

            modelBuilder.Entity("Caliber.Api.Domain.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Caliber.Api.Domain.CertificationAward", b =>
                {
                    b.HasOne("Caliber.Api.Domain.EmployeeCertification", "EmployeeCertification")
                        .WithMany("Awards")
                        .HasForeignKey("EmployeeCertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeCertification");
                });

            modelBuilder.Entity("Caliber.Api.Domain.CertificationSkill", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Certification", "Certification")
                        .WithMany("GrantedSkills")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Skill", "Skill")
                        .WithMany("GrantedByCertifications")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Employee", b =>
                {
                    b.HasOne("Caliber.Api.Domain.JobRole", "JobRole")
                        .WithMany("Employees")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobRole");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeCertification", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Certification", "Certification")
                        .WithMany("Assignments")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeSkill", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Certification", "SourceCertification")
                        .WithMany()
                        .HasForeignKey("SourceCertificationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.EmployeeCertification", "SourceEmployeeCertification")
                        .WithMany()
                        .HasForeignKey("SourceEmployeeCertificationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.EmployeeTraining", "SourceEmployeeTraining")
                        .WithMany()
                        .HasForeignKey("SourceEmployeeTrainingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.TrainingProgram", "SourceTrainingProgram")
                        .WithMany()
                        .HasForeignKey("SourceTrainingProgramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");

                    b.Navigation("Skill");

                    b.Navigation("SourceCertification");

                    b.Navigation("SourceEmployeeCertification");

                    b.Navigation("SourceEmployeeTraining");

                    b.Navigation("SourceTrainingProgram");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeTraining", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithMany("Trainings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany("Assignments")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Evidence", b =>
                {
                    b.HasOne("Caliber.Api.Domain.EmployeeCertification", "EmployeeCertification")
                        .WithMany("Evidence")
                        .HasForeignKey("EmployeeCertificationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithMany("Evidence")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.EmployeeSkill", "EmployeeSkill")
                        .WithMany("Evidence")
                        .HasForeignKey("EmployeeSkillId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.EmployeeTraining", "EmployeeTraining")
                        .WithMany("Evidence")
                        .HasForeignKey("EmployeeTrainingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");

                    b.Navigation("EmployeeCertification");

                    b.Navigation("EmployeeSkill");

                    b.Navigation("EmployeeTraining");
                });

            modelBuilder.Entity("Caliber.Api.Domain.JobRole", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Department", "Department")
                        .WithMany("JobRoles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Caliber.Api.Domain.RoleRequirement", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Caliber.Api.Domain.JobRole", "JobRole")
                        .WithMany("Requirements")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Caliber.Api.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany()
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Certification");

                    b.Navigation("JobRole");

                    b.Navigation("Skill");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Caliber.Api.Domain.SkillAssignmentRequest", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Employee", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.Employee", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caliber.Api.Domain.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("RequestedBy");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingModule", b =>
                {
                    b.HasOne("Caliber.Api.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany("Modules")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingProgramSkill", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Skill", "Skill")
                        .WithMany("GrantedByTraining")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caliber.Api.Domain.TrainingProgram", "TrainingProgram")
                        .WithMany("GrantedSkills")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Caliber.Api.Domain.UserAccount", b =>
                {
                    b.HasOne("Caliber.Api.Domain.Employee", "Employee")
                        .WithOne("UserAccount")
                        .HasForeignKey("Caliber.Api.Domain.UserAccount", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Certification", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("GrantedSkills");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Department", b =>
                {
                    b.Navigation("JobRoles");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Employee", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Evidence");

                    b.Navigation("Skills");

                    b.Navigation("Trainings");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeCertification", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeSkill", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Caliber.Api.Domain.EmployeeTraining", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Caliber.Api.Domain.JobRole", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Location", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Caliber.Api.Domain.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");

                    b.Navigation("GrantedByCertifications");

                    b.Navigation("GrantedByTraining");
                });

            modelBuilder.Entity("Caliber.Api.Domain.TrainingProgram", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("GrantedSkills");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
